<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs\Frequency;

use UnexpectedValueException;

/**
 * Protobuf type <code>gtfs.Frequency.ScheduleType</code>
 */
class ScheduleType
{
    /**
     * Generated from protobuf enum <code>NOT_EXACTLY = 0;</code>
     */
    const NOT_EXACTLY = 0;
    /**
     * Generated from protobuf enum <code>EXACTLY = 1;</code>
     */
    const EXACTLY = 1;

    private static $valueToName = [
        self::NOT_EXACTLY => 'NOT_EXACTLY',
        self::EXACTLY => 'EXACTLY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ScheduleType::class, \Gtfs\Frequency_ScheduleType::class);

