<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs\Calendar;

use UnexpectedValueException;

/**
 * Protobuf type <code>gtfs.Calendar.CalendarDay</code>
 */
class CalendarDay
{
    /**
     * Generated from protobuf enum <code>NOT_AVAILABLE = 0;</code>
     */
    const NOT_AVAILABLE = 0;
    /**
     * Generated from protobuf enum <code>AVAILABLE = 1;</code>
     */
    const AVAILABLE = 1;

    private static $valueToName = [
        self::NOT_AVAILABLE => 'NOT_AVAILABLE',
        self::AVAILABLE => 'AVAILABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CalendarDay::class, \Gtfs\Calendar_CalendarDay::class);

