<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs;

if (false) {
    /**
     * This class is deprecated. Use Gtfs\CalendarDate\ExceptionType instead.
     * @deprecated
     */
    class CalendarDate_ExceptionType {}
}
class_exists(CalendarDate\ExceptionType::class);
@trigger_error('Gtfs\CalendarDate_ExceptionType is deprecated and will be removed in the next major release. Use Gtfs\CalendarDate\ExceptionType instead', E_USER_DEPRECATED);

