<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs;

if (false) {
    /**
     * This class is deprecated. Use Gtfs\Calendar\CalendarDay instead.
     * @deprecated
     */
    class Calendar_CalendarDay {}
}
class_exists(Calendar\CalendarDay::class);
@trigger_error('Gtfs\Calendar_CalendarDay is deprecated and will be removed in the next major release. Use Gtfs\Calendar\CalendarDay instead', E_USER_DEPRECATED);

