<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs;

if (false) {
    /**
     * This class is deprecated. Use Gtfs\FareAttribute\PaymentMethod instead.
     * @deprecated
     */
    class FareAttribute_PaymentMethod {}
}
class_exists(FareAttribute\PaymentMethod::class);
@trigger_error('Gtfs\FareAttribute_PaymentMethod is deprecated and will be removed in the next major release. Use Gtfs\FareAttribute\PaymentMethod instead', E_USER_DEPRECATED);

