<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs;

if (false) {
    /**
     * This class is deprecated. Use Gtfs\FareAttribute\Transfers instead.
     * @deprecated
     */
    class FareAttribute_Transfers {}
}
class_exists(FareAttribute\Transfers::class);
@trigger_error('Gtfs\FareAttribute_Transfers is deprecated and will be removed in the next major release. Use Gtfs\FareAttribute\Transfers instead', E_USER_DEPRECATED);

