<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs;

if (false) {
    /**
     * This class is deprecated. Use Gtfs\Route\RouteType instead.
     * @deprecated
     */
    class Route_RouteType {}
}
class_exists(Route\RouteType::class);
@trigger_error('Gtfs\Route_RouteType is deprecated and will be removed in the next major release. Use Gtfs\Route\RouteType instead', E_USER_DEPRECATED);

