<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs;

if (false) {
    /**
     * This class is deprecated. Use Gtfs\Stop\WheelchairBoarding instead.
     * @deprecated
     */
    class Stop_WheelchairBoarding {}
}
class_exists(Stop\WheelchairBoarding::class);
@trigger_error('Gtfs\Stop_WheelchairBoarding is deprecated and will be removed in the next major release. Use Gtfs\Stop\WheelchairBoarding instead', E_USER_DEPRECATED);

