<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs;

if (false) {
    /**
     * This class is deprecated. Use Gtfs\StopTime\AvailabilityType instead.
     * @deprecated
     */
    class StopTime_AvailabilityType {}
}
class_exists(StopTime\AvailabilityType::class);
@trigger_error('Gtfs\StopTime_AvailabilityType is deprecated and will be removed in the next major release. Use Gtfs\StopTime\AvailabilityType instead', E_USER_DEPRECATED);

