<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>gtfs.Transfer</code>
 */
class Transfer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string from_stop_id = 1;</code>
     */
    protected $from_stop_id = '';
    /**
     * Generated from protobuf field <code>string to_stop_id = 2;</code>
     */
    protected $to_stop_id = '';
    /**
     * Generated from protobuf field <code>.gtfs.Transfer.TransferType transfer_type = 3;</code>
     */
    protected $transfer_type = 0;
    /**
     * Generated from protobuf field <code>int32 min_transfer_time = 4;</code>
     */
    protected $min_transfer_time = 0;
    /**
     * The extensions namespace allows 3rd-party developers to extend the
     * GTFS specification in order to add and evaluate new features and
     * modifications to the spec.
     *
     * Generated from protobuf field <code>.google.protobuf.Any extension = 2000;</code>
     */
    protected $extension = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $from_stop_id
     *     @type string $to_stop_id
     *     @type int $transfer_type
     *     @type int $min_transfer_time
     *     @type \Google\Protobuf\Any $extension
     *           The extensions namespace allows 3rd-party developers to extend the
     *           GTFS specification in order to add and evaluate new features and
     *           modifications to the spec.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Gtfs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string from_stop_id = 1;</code>
     * @return string
     */
    public function getFromStopId()
    {
        return $this->from_stop_id;
    }

    /**
     * Generated from protobuf field <code>string from_stop_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFromStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->from_stop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to_stop_id = 2;</code>
     * @return string
     */
    public function getToStopId()
    {
        return $this->to_stop_id;
    }

    /**
     * Generated from protobuf field <code>string to_stop_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_stop_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.gtfs.Transfer.TransferType transfer_type = 3;</code>
     * @return int
     */
    public function getTransferType()
    {
        return $this->transfer_type;
    }

    /**
     * Generated from protobuf field <code>.gtfs.Transfer.TransferType transfer_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTransferType($var)
    {
        GPBUtil::checkEnum($var, \Gtfs\Transfer_TransferType::class);
        $this->transfer_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 min_transfer_time = 4;</code>
     * @return int
     */
    public function getMinTransferTime()
    {
        return $this->min_transfer_time;
    }

    /**
     * Generated from protobuf field <code>int32 min_transfer_time = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMinTransferTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_transfer_time = $var;

        return $this;
    }

    /**
     * The extensions namespace allows 3rd-party developers to extend the
     * GTFS specification in order to add and evaluate new features and
     * modifications to the spec.
     *
     * Generated from protobuf field <code>.google.protobuf.Any extension = 2000;</code>
     * @return \Google\Protobuf\Any
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * The extensions namespace allows 3rd-party developers to extend the
     * GTFS specification in order to add and evaluate new features and
     * modifications to the spec.
     *
     * Generated from protobuf field <code>.google.protobuf.Any extension = 2000;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setExtension($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->extension = $var;

        return $this;
    }

}

