<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gtfs.proto

namespace Gtfs;

if (false) {
    /**
     * This class is deprecated. Use Gtfs\Transfer\TransferType instead.
     * @deprecated
     */
    class Transfer_TransferType {}
}
class_exists(Transfer\TransferType::class);
@trigger_error('Gtfs\Transfer_TransferType is deprecated and will be removed in the next major release. Use Gtfs\Transfer\TransferType instead', E_USER_DEPRECATED);

